- name: When condition with FACT variables
  hosts: webserver
  become: true
  tasks:
  - name: Install httpd package on the server
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"
  - name: Install apache2 package on the server
    apt: name=apache2 state=present
    when: ansible_os_family != "RedHat"
